{% set name = "guile" %}
{% set version = "3.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 04485e759b2aec44e33cdd06ece28bbb859c1dbef73e8aeac02e4e7ca2fe0e57
  patches:
    - skip_posix_crypt_test.patch  # [linux]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - sed  # [osx]
    - libunistring
    - libffi
    - bdw-gc
    - gmp
    - libiconv
    - readline
    - libtool
    - pkg-config
    - gettext
  run:
    - libunistring
    - libtool
    - libffi
    - bdw-gc
    - gmp
    - libiconv
    - readline
    - gettext

test:
  commands:
    - guile -v

about:
  home: https://www.gnu.org/software/guile
  license: LGPL-3.0
  license_file: LICENSE
  license_family: LGPL
  summary: The GNU C implementation of the Scheme programming language
  doc_url: https://www.gnu.org/software/guile/manual/

extra:
  recipe-maintainers:
    - ChristopherHogan
