schema_version: 1

context:
  version: 3.0.10

package:
  name: guile
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/guile/guile-${{ version }}.tar.gz
  sha256: 2dbdbc97598b2faf31013564efb48e4fed44131d28e996c26abe8a5b23b56c2a

build:
  number: 1
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - gettext-tools
    - make
    - pkg-config
    - sed
    - if: build_platform != target_platform
      then:
        - bdw-gc
        - gmp
        - libffi
        - libiconv
        - libunistring
        - readline
        - if: osx
          then: libintl-devel
  host:
    - bdw-gc
    - gmp
    - libatomic_ops
    - libffi
    - libiconv
    - libtool
    - libunistring
    - ncurses
    - readline
    - if: linux
      then: libxcrypt
    - if: osx
      then: libintl-devel

tests:
  - script:
      - guile -v

about:
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: The GNU C implementation of the Scheme programming language
  homepage: https://www.gnu.org/software/guile
  documentation: https://www.gnu.org/software/guile/manual/

extra:
  recipe-maintainers:
    - danielnachun
    - ChristopherHogan
