travis:
  secure:
    BINSTAR_TOKEN: SUVAfuvDGlfYl1wTv8HF+nbose0YiVCVagzY+OV8lz6rU9j8S0YY20qV9h1Nz3FGmE0oRQClQrCXx0lGkms9lbxKuZmJp9T83b1527lSLGAjCK1KwOLJ3YwiIbTs8agcyrTR2b1t2NGy/RXJVHt+TNXc6o1cDqF/rg3Dfyi1Jy+xpJZvnG6h+I1GvInDdRpxRogcfk+Y6mIq/p/JBueInaTbptd2o+ia/4L12R1cNT3h9SJGsE46vMT35WgbiTwcM5i/EqXf/TSPe43+jiN1JGWg4I/uQ0fFG00YR9at8Afacdnto1GGB4JkDb3N683/6UTILu9agBU6jjyfs1S9IiQ1apaU3N35AQHP+62NLEpBanFrGni3p7ThuG1WVBOVGKP5mkfAwwRaNVoo5jB4pcbZpTa4nOaaks+m6TARXgquIm0NYK1eS9oIkk/T8HW4fzE2mGPdu41kPQPFoYVUGvdezhJ42FNEBPb4uUoXEc0H5+6mx/9k1QiTO4IEfNxSs+CoQDWBNt5G+cCrNNGLXt+nRrPz2zrCaKnkfoo61o3hTCfaFs066E2/ikbX47gOpio+ejXmzyzC6zmuLxhewzsnbvOkEJWSXp5itcUx1hDZDsEcDwMMN+aodnnqwwqZ4ohKdZTKTx3sGdxqDU1ks8Ce9IYqadG59vMQkBgialA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
